
#pragma once

#include <QString>

#define I18N_NOOP2(_a, _b) _b

inline QString i18n (const char *text)
{
    return QString(QLatin1String(text));
}

template <typename A1>
inline QString i18n (const char *text, const A1 &a1)
{
    return QString(QLatin1String(text)).arg(a1);
}
// Autogenerated; contact KLocalizedString maintainer for batch changes.
/**
 * Returns a localized version of a string with 2 arguments.
 * @param text string to be localized
 * @param a1 first argument
 * @param a2 second argument
 * @return localized string
 */
template <typename A1, typename A2>
inline QString i18n (const char *text, const A1 &a1, const A2 &a2)
{
    return QString(QLatin1String(text)).arg(a1).arg(a2);
}
// Autogenerated; contact KLocalizedString maintainer for batch changes.
/**
 * Returns a localized version of a string with 3 arguments.
 * @param text string to be localized
 * @param a1 first argument
 * @param a2 second argument
 * @param a3 third argument
 * @return localized string
 */
template <typename A1, typename A2, typename A3>
inline QString i18n (const char *text, const A1 &a1, const A2 &a2, const A3 &a3)
{
    return QString(QLatin1String(text)).arg(a1).arg(a2).arg(a3);
}

template <typename A1>
inline QString i18nc(const char*, const char* text, const A1 &a1)
{
    return QString(QLatin1String(text)).arg(a1);
}

inline QString i18nc(const char*, const char* text)
{
    return QString(QLatin1String(text));
}
