// This file was generated by ecm_qt_declare_logging_category(): DO NOT EDIT!

#include "kconfigwidgets_debug.h"


#if QT_VERSION >= QT_VERSION_CHECK(5, 4, 0)
Q_LOGGING_CATEGORY(KCONFIG_WIDGETS_LOG, "kf5.kconfigwidgets", QtInfoMsg)
#else
Q_LOGGING_CATEGORY(KCONFIG_WIDGETS_LOG, "kf5.kconfigwidgets")
#endif

