// This file was generated by ecm_qt_declare_logging_category(): DO NOT EDIT!

#ifndef ECM_QLOGGINGCATEGORY_KWIDGETSADDONSLOG_LOGGINGCATEGORY_H
#define ECM_QLOGGINGCATEGORY_KWIDGETSADDONSLOG_LOGGINGCATEGORY_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(KWidgetsAddonsLog)


#endif
