// This file was generated by ecm_qt_declare_logging_category(): DO NOT EDIT!

#include "kconfig_core_log_settings.h"


#if QT_VERSION >= QT_VERSION_CHECK(5, 4, 0)
Q_LOGGING_CATEGORY(KCONFIG_CORE_LOG, "kf5.kconfig.core", QtInfoMsg)
#else
Q_LOGGING_CATEGORY(KCONFIG_CORE_LOG, "kf5.kconfig.core")
#endif

