// This file was generated by ecm_qt_declare_logging_category(): DO NOT EDIT!

#ifndef ECM_QLOGGINGCATEGORY_KI18N_KI18N_LOGGING_H
#define ECM_QLOGGINGCATEGORY_KI18N_KI18N_LOGGING_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(KI18N)


#endif
