// This file was generated by ecm_qt_declare_logging_category(): DO NOT EDIT!

#include "ki18n_logging_kuit.h"


#if QT_VERSION >= QT_VERSION_CHECK(5, 4, 0)
Q_LOGGING_CATEGORY(KI18N_KUIT, "kf5.ki18n.kuit", QtInfoMsg)
#else
Q_LOGGING_CATEGORY(KI18N_KUIT, "kf5.ki18n.kuit")
#endif

