// This file was generated by ecm_qt_declare_logging_category(): DO NOT EDIT!

#include "TerminalDebug.h"


#if QT_VERSION >= QT_VERSION_CHECK(5, 4, 0)
Q_LOGGING_CATEGORY(TerminalDebug, "org.kde.konsole", QtInfoMsg)
#else
Q_LOGGING_CATEGORY(TerminalDebug, "org.kde.konsole")
#endif

